// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package loan

import (
	fmt "fmt"
	io "io"
	reflect "reflect"
	sync "sync"

	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

var (
	md_CreditCardMetadata                 protoreflect.MessageDescriptor
	fd_CreditCardMetadata_index           protoreflect.FieldDescriptor
	fd_CreditCardMetadata_loanId          protoreflect.FieldDescriptor
	fd_CreditCardMetadata_creditLimit     protoreflect.FieldDescriptor
	fd_CreditCardMetadata_availableCredit protoreflect.FieldDescriptor
	fd_CreditCardMetadata_minimumPayment  protoreflect.FieldDescriptor
	fd_CreditCardMetadata_dailyRate       protoreflect.FieldDescriptor
	fd_CreditCardMetadata_gracePeriodDays protoreflect.FieldDescriptor
	fd_CreditCardMetadata_overlimitFee    protoreflect.FieldDescriptor
	fd_CreditCardMetadata_lateFee         protoreflect.FieldDescriptor
	fd_CreditCardMetadata_creator         protoreflect.FieldDescriptor
)

func init() {
	file_ardaos_loan_credit_card_metadata_proto_init()
	md_CreditCardMetadata = File_ardaos_loan_credit_card_metadata_proto.Messages().ByName("CreditCardMetadata")
	fd_CreditCardMetadata_index = md_CreditCardMetadata.Fields().ByName("index")
	fd_CreditCardMetadata_loanId = md_CreditCardMetadata.Fields().ByName("loanId")
	fd_CreditCardMetadata_creditLimit = md_CreditCardMetadata.Fields().ByName("creditLimit")
	fd_CreditCardMetadata_availableCredit = md_CreditCardMetadata.Fields().ByName("availableCredit")
	fd_CreditCardMetadata_minimumPayment = md_CreditCardMetadata.Fields().ByName("minimumPayment")
	fd_CreditCardMetadata_dailyRate = md_CreditCardMetadata.Fields().ByName("dailyRate")
	fd_CreditCardMetadata_gracePeriodDays = md_CreditCardMetadata.Fields().ByName("gracePeriodDays")
	fd_CreditCardMetadata_overlimitFee = md_CreditCardMetadata.Fields().ByName("overlimitFee")
	fd_CreditCardMetadata_lateFee = md_CreditCardMetadata.Fields().ByName("lateFee")
	fd_CreditCardMetadata_creator = md_CreditCardMetadata.Fields().ByName("creator")
}

var _ protoreflect.Message = (*fastReflection_CreditCardMetadata)(nil)

type fastReflection_CreditCardMetadata CreditCardMetadata

func (x *CreditCardMetadata) ProtoReflect() protoreflect.Message {
	return (*fastReflection_CreditCardMetadata)(x)
}

func (x *CreditCardMetadata) slowProtoReflect() protoreflect.Message {
	mi := &file_ardaos_loan_credit_card_metadata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_CreditCardMetadata_messageType fastReflection_CreditCardMetadata_messageType
var _ protoreflect.MessageType = fastReflection_CreditCardMetadata_messageType{}

type fastReflection_CreditCardMetadata_messageType struct{}

func (x fastReflection_CreditCardMetadata_messageType) Zero() protoreflect.Message {
	return (*fastReflection_CreditCardMetadata)(nil)
}
func (x fastReflection_CreditCardMetadata_messageType) New() protoreflect.Message {
	return new(fastReflection_CreditCardMetadata)
}
func (x fastReflection_CreditCardMetadata_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_CreditCardMetadata
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_CreditCardMetadata) Descriptor() protoreflect.MessageDescriptor {
	return md_CreditCardMetadata
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_CreditCardMetadata) Type() protoreflect.MessageType {
	return _fastReflection_CreditCardMetadata_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_CreditCardMetadata) New() protoreflect.Message {
	return new(fastReflection_CreditCardMetadata)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_CreditCardMetadata) Interface() protoreflect.ProtoMessage {
	return (*CreditCardMetadata)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_CreditCardMetadata) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Index != "" {
		value := protoreflect.ValueOfString(x.Index)
		if !f(fd_CreditCardMetadata_index, value) {
			return
		}
	}
	if x.LoanId != "" {
		value := protoreflect.ValueOfString(x.LoanId)
		if !f(fd_CreditCardMetadata_loanId, value) {
			return
		}
	}
	if x.CreditLimit != uint64(0) {
		value := protoreflect.ValueOfUint64(x.CreditLimit)
		if !f(fd_CreditCardMetadata_creditLimit, value) {
			return
		}
	}
	if x.AvailableCredit != uint64(0) {
		value := protoreflect.ValueOfUint64(x.AvailableCredit)
		if !f(fd_CreditCardMetadata_availableCredit, value) {
			return
		}
	}
	if x.MinimumPayment != uint64(0) {
		value := protoreflect.ValueOfUint64(x.MinimumPayment)
		if !f(fd_CreditCardMetadata_minimumPayment, value) {
			return
		}
	}
	if x.DailyRate != "" {
		value := protoreflect.ValueOfString(x.DailyRate)
		if !f(fd_CreditCardMetadata_dailyRate, value) {
			return
		}
	}
	if x.GracePeriodDays != uint32(0) {
		value := protoreflect.ValueOfUint32(x.GracePeriodDays)
		if !f(fd_CreditCardMetadata_gracePeriodDays, value) {
			return
		}
	}
	if x.OverlimitFee != uint64(0) {
		value := protoreflect.ValueOfUint64(x.OverlimitFee)
		if !f(fd_CreditCardMetadata_overlimitFee, value) {
			return
		}
	}
	if x.LateFee != uint64(0) {
		value := protoreflect.ValueOfUint64(x.LateFee)
		if !f(fd_CreditCardMetadata_lateFee, value) {
			return
		}
	}
	if x.Creator != "" {
		value := protoreflect.ValueOfString(x.Creator)
		if !f(fd_CreditCardMetadata_creator, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_CreditCardMetadata) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "ardaos.loan.CreditCardMetadata.index":
		return x.Index != ""
	case "ardaos.loan.CreditCardMetadata.loanId":
		return x.LoanId != ""
	case "ardaos.loan.CreditCardMetadata.creditLimit":
		return x.CreditLimit != uint64(0)
	case "ardaos.loan.CreditCardMetadata.availableCredit":
		return x.AvailableCredit != uint64(0)
	case "ardaos.loan.CreditCardMetadata.minimumPayment":
		return x.MinimumPayment != uint64(0)
	case "ardaos.loan.CreditCardMetadata.dailyRate":
		return x.DailyRate != ""
	case "ardaos.loan.CreditCardMetadata.gracePeriodDays":
		return x.GracePeriodDays != uint32(0)
	case "ardaos.loan.CreditCardMetadata.overlimitFee":
		return x.OverlimitFee != uint64(0)
	case "ardaos.loan.CreditCardMetadata.lateFee":
		return x.LateFee != uint64(0)
	case "ardaos.loan.CreditCardMetadata.creator":
		return x.Creator != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ardaos.loan.CreditCardMetadata"))
		}
		panic(fmt.Errorf("message ardaos.loan.CreditCardMetadata does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_CreditCardMetadata) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "ardaos.loan.CreditCardMetadata.index":
		x.Index = ""
	case "ardaos.loan.CreditCardMetadata.loanId":
		x.LoanId = ""
	case "ardaos.loan.CreditCardMetadata.creditLimit":
		x.CreditLimit = uint64(0)
	case "ardaos.loan.CreditCardMetadata.availableCredit":
		x.AvailableCredit = uint64(0)
	case "ardaos.loan.CreditCardMetadata.minimumPayment":
		x.MinimumPayment = uint64(0)
	case "ardaos.loan.CreditCardMetadata.dailyRate":
		x.DailyRate = ""
	case "ardaos.loan.CreditCardMetadata.gracePeriodDays":
		x.GracePeriodDays = uint32(0)
	case "ardaos.loan.CreditCardMetadata.overlimitFee":
		x.OverlimitFee = uint64(0)
	case "ardaos.loan.CreditCardMetadata.lateFee":
		x.LateFee = uint64(0)
	case "ardaos.loan.CreditCardMetadata.creator":
		x.Creator = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ardaos.loan.CreditCardMetadata"))
		}
		panic(fmt.Errorf("message ardaos.loan.CreditCardMetadata does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_CreditCardMetadata) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "ardaos.loan.CreditCardMetadata.index":
		value := x.Index
		return protoreflect.ValueOfString(value)
	case "ardaos.loan.CreditCardMetadata.loanId":
		value := x.LoanId
		return protoreflect.ValueOfString(value)
	case "ardaos.loan.CreditCardMetadata.creditLimit":
		value := x.CreditLimit
		return protoreflect.ValueOfUint64(value)
	case "ardaos.loan.CreditCardMetadata.availableCredit":
		value := x.AvailableCredit
		return protoreflect.ValueOfUint64(value)
	case "ardaos.loan.CreditCardMetadata.minimumPayment":
		value := x.MinimumPayment
		return protoreflect.ValueOfUint64(value)
	case "ardaos.loan.CreditCardMetadata.dailyRate":
		value := x.DailyRate
		return protoreflect.ValueOfString(value)
	case "ardaos.loan.CreditCardMetadata.gracePeriodDays":
		value := x.GracePeriodDays
		return protoreflect.ValueOfUint32(value)
	case "ardaos.loan.CreditCardMetadata.overlimitFee":
		value := x.OverlimitFee
		return protoreflect.ValueOfUint64(value)
	case "ardaos.loan.CreditCardMetadata.lateFee":
		value := x.LateFee
		return protoreflect.ValueOfUint64(value)
	case "ardaos.loan.CreditCardMetadata.creator":
		value := x.Creator
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ardaos.loan.CreditCardMetadata"))
		}
		panic(fmt.Errorf("message ardaos.loan.CreditCardMetadata does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_CreditCardMetadata) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "ardaos.loan.CreditCardMetadata.index":
		x.Index = value.Interface().(string)
	case "ardaos.loan.CreditCardMetadata.loanId":
		x.LoanId = value.Interface().(string)
	case "ardaos.loan.CreditCardMetadata.creditLimit":
		x.CreditLimit = value.Uint()
	case "ardaos.loan.CreditCardMetadata.availableCredit":
		x.AvailableCredit = value.Uint()
	case "ardaos.loan.CreditCardMetadata.minimumPayment":
		x.MinimumPayment = value.Uint()
	case "ardaos.loan.CreditCardMetadata.dailyRate":
		x.DailyRate = value.Interface().(string)
	case "ardaos.loan.CreditCardMetadata.gracePeriodDays":
		x.GracePeriodDays = uint32(value.Uint())
	case "ardaos.loan.CreditCardMetadata.overlimitFee":
		x.OverlimitFee = value.Uint()
	case "ardaos.loan.CreditCardMetadata.lateFee":
		x.LateFee = value.Uint()
	case "ardaos.loan.CreditCardMetadata.creator":
		x.Creator = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ardaos.loan.CreditCardMetadata"))
		}
		panic(fmt.Errorf("message ardaos.loan.CreditCardMetadata does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_CreditCardMetadata) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "ardaos.loan.CreditCardMetadata.index":
		panic(fmt.Errorf("field index of message ardaos.loan.CreditCardMetadata is not mutable"))
	case "ardaos.loan.CreditCardMetadata.loanId":
		panic(fmt.Errorf("field loanId of message ardaos.loan.CreditCardMetadata is not mutable"))
	case "ardaos.loan.CreditCardMetadata.creditLimit":
		panic(fmt.Errorf("field creditLimit of message ardaos.loan.CreditCardMetadata is not mutable"))
	case "ardaos.loan.CreditCardMetadata.availableCredit":
		panic(fmt.Errorf("field availableCredit of message ardaos.loan.CreditCardMetadata is not mutable"))
	case "ardaos.loan.CreditCardMetadata.minimumPayment":
		panic(fmt.Errorf("field minimumPayment of message ardaos.loan.CreditCardMetadata is not mutable"))
	case "ardaos.loan.CreditCardMetadata.dailyRate":
		panic(fmt.Errorf("field dailyRate of message ardaos.loan.CreditCardMetadata is not mutable"))
	case "ardaos.loan.CreditCardMetadata.gracePeriodDays":
		panic(fmt.Errorf("field gracePeriodDays of message ardaos.loan.CreditCardMetadata is not mutable"))
	case "ardaos.loan.CreditCardMetadata.overlimitFee":
		panic(fmt.Errorf("field overlimitFee of message ardaos.loan.CreditCardMetadata is not mutable"))
	case "ardaos.loan.CreditCardMetadata.lateFee":
		panic(fmt.Errorf("field lateFee of message ardaos.loan.CreditCardMetadata is not mutable"))
	case "ardaos.loan.CreditCardMetadata.creator":
		panic(fmt.Errorf("field creator of message ardaos.loan.CreditCardMetadata is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ardaos.loan.CreditCardMetadata"))
		}
		panic(fmt.Errorf("message ardaos.loan.CreditCardMetadata does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_CreditCardMetadata) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "ardaos.loan.CreditCardMetadata.index":
		return protoreflect.ValueOfString("")
	case "ardaos.loan.CreditCardMetadata.loanId":
		return protoreflect.ValueOfString("")
	case "ardaos.loan.CreditCardMetadata.creditLimit":
		return protoreflect.ValueOfUint64(uint64(0))
	case "ardaos.loan.CreditCardMetadata.availableCredit":
		return protoreflect.ValueOfUint64(uint64(0))
	case "ardaos.loan.CreditCardMetadata.minimumPayment":
		return protoreflect.ValueOfUint64(uint64(0))
	case "ardaos.loan.CreditCardMetadata.dailyRate":
		return protoreflect.ValueOfString("")
	case "ardaos.loan.CreditCardMetadata.gracePeriodDays":
		return protoreflect.ValueOfUint32(uint32(0))
	case "ardaos.loan.CreditCardMetadata.overlimitFee":
		return protoreflect.ValueOfUint64(uint64(0))
	case "ardaos.loan.CreditCardMetadata.lateFee":
		return protoreflect.ValueOfUint64(uint64(0))
	case "ardaos.loan.CreditCardMetadata.creator":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ardaos.loan.CreditCardMetadata"))
		}
		panic(fmt.Errorf("message ardaos.loan.CreditCardMetadata does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_CreditCardMetadata) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in ardaos.loan.CreditCardMetadata", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_CreditCardMetadata) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_CreditCardMetadata) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_CreditCardMetadata) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_CreditCardMetadata) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*CreditCardMetadata)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Index)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.LoanId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.CreditLimit != 0 {
			n += 1 + runtime.Sov(uint64(x.CreditLimit))
		}
		if x.AvailableCredit != 0 {
			n += 1 + runtime.Sov(uint64(x.AvailableCredit))
		}
		if x.MinimumPayment != 0 {
			n += 1 + runtime.Sov(uint64(x.MinimumPayment))
		}
		l = len(x.DailyRate)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.GracePeriodDays != 0 {
			n += 1 + runtime.Sov(uint64(x.GracePeriodDays))
		}
		if x.OverlimitFee != 0 {
			n += 1 + runtime.Sov(uint64(x.OverlimitFee))
		}
		if x.LateFee != 0 {
			n += 1 + runtime.Sov(uint64(x.LateFee))
		}
		l = len(x.Creator)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*CreditCardMetadata)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Creator) > 0 {
			i -= len(x.Creator)
			copy(dAtA[i:], x.Creator)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Creator)))
			i--
			dAtA[i] = 0x52
		}
		if x.LateFee != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.LateFee))
			i--
			dAtA[i] = 0x48
		}
		if x.OverlimitFee != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.OverlimitFee))
			i--
			dAtA[i] = 0x40
		}
		if x.GracePeriodDays != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.GracePeriodDays))
			i--
			dAtA[i] = 0x38
		}
		if len(x.DailyRate) > 0 {
			i -= len(x.DailyRate)
			copy(dAtA[i:], x.DailyRate)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.DailyRate)))
			i--
			dAtA[i] = 0x32
		}
		if x.MinimumPayment != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.MinimumPayment))
			i--
			dAtA[i] = 0x28
		}
		if x.AvailableCredit != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.AvailableCredit))
			i--
			dAtA[i] = 0x20
		}
		if x.CreditLimit != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.CreditLimit))
			i--
			dAtA[i] = 0x18
		}
		if len(x.LoanId) > 0 {
			i -= len(x.LoanId)
			copy(dAtA[i:], x.LoanId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.LoanId)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Index) > 0 {
			i -= len(x.Index)
			copy(dAtA[i:], x.Index)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Index)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*CreditCardMetadata)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: CreditCardMetadata: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: CreditCardMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Index = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field LoanId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.LoanId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field CreditLimit", wireType)
				}
				x.CreditLimit = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.CreditLimit |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 4:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field AvailableCredit", wireType)
				}
				x.AvailableCredit = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.AvailableCredit |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 5:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field MinimumPayment", wireType)
				}
				x.MinimumPayment = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.MinimumPayment |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field DailyRate", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.DailyRate = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 7:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field GracePeriodDays", wireType)
				}
				x.GracePeriodDays = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.GracePeriodDays |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 8:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field OverlimitFee", wireType)
				}
				x.OverlimitFee = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.OverlimitFee |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 9:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field LateFee", wireType)
				}
				x.LateFee = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.LateFee |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 10:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Creator = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: ardaos/loan/credit_card_metadata.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreditCardMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index           string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	LoanId          string `protobuf:"bytes,2,opt,name=loanId,proto3" json:"loanId,omitempty"`
	CreditLimit     uint64 `protobuf:"varint,3,opt,name=creditLimit,proto3" json:"creditLimit,omitempty"`
	AvailableCredit uint64 `protobuf:"varint,4,opt,name=availableCredit,proto3" json:"availableCredit,omitempty"`
	MinimumPayment  uint64 `protobuf:"varint,5,opt,name=minimumPayment,proto3" json:"minimumPayment,omitempty"`
	DailyRate       string `protobuf:"bytes,6,opt,name=dailyRate,proto3" json:"dailyRate,omitempty"`
	GracePeriodDays uint32 `protobuf:"varint,7,opt,name=gracePeriodDays,proto3" json:"gracePeriodDays,omitempty"`
	OverlimitFee    uint64 `protobuf:"varint,8,opt,name=overlimitFee,proto3" json:"overlimitFee,omitempty"`
	LateFee         uint64 `protobuf:"varint,9,opt,name=lateFee,proto3" json:"lateFee,omitempty"`
	Creator         string `protobuf:"bytes,10,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (x *CreditCardMetadata) Reset() {
	*x = CreditCardMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ardaos_loan_credit_card_metadata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreditCardMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditCardMetadata) ProtoMessage() {}

// Deprecated: Use CreditCardMetadata.ProtoReflect.Descriptor instead.
func (*CreditCardMetadata) Descriptor() ([]byte, []int) {
	return file_ardaos_loan_credit_card_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *CreditCardMetadata) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *CreditCardMetadata) GetLoanId() string {
	if x != nil {
		return x.LoanId
	}
	return ""
}

func (x *CreditCardMetadata) GetCreditLimit() uint64 {
	if x != nil {
		return x.CreditLimit
	}
	return 0
}

func (x *CreditCardMetadata) GetAvailableCredit() uint64 {
	if x != nil {
		return x.AvailableCredit
	}
	return 0
}

func (x *CreditCardMetadata) GetMinimumPayment() uint64 {
	if x != nil {
		return x.MinimumPayment
	}
	return 0
}

func (x *CreditCardMetadata) GetDailyRate() string {
	if x != nil {
		return x.DailyRate
	}
	return ""
}

func (x *CreditCardMetadata) GetGracePeriodDays() uint32 {
	if x != nil {
		return x.GracePeriodDays
	}
	return 0
}

func (x *CreditCardMetadata) GetOverlimitFee() uint64 {
	if x != nil {
		return x.OverlimitFee
	}
	return 0
}

func (x *CreditCardMetadata) GetLateFee() uint64 {
	if x != nil {
		return x.LateFee
	}
	return 0
}

func (x *CreditCardMetadata) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

var File_ardaos_loan_credit_card_metadata_proto protoreflect.FileDescriptor

var file_ardaos_loan_credit_card_metadata_proto_rawDesc = []byte{
	0x0a, 0x26, 0x61, 0x72, 0x64, 0x61, 0x6f, 0x73, 0x2f, 0x6c, 0x6f, 0x61, 0x6e, 0x2f, 0x63, 0x72,
	0x65, 0x64, 0x69, 0x74, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x72, 0x64, 0x61, 0x6f, 0x73,
	0x2e, 0x6c, 0x6f, 0x61, 0x6e, 0x22, 0xd6, 0x02, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74,
	0x43, 0x61, 0x72, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x61, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6c, 0x6f, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x72,
	0x65, 0x64, 0x69, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0b, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x28, 0x0a, 0x0f,
	0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75,
	0x6d, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e,
	0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x64, 0x61, 0x69, 0x6c, 0x79, 0x52, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x64, 0x61, 0x69, 0x6c, 0x79, 0x52, 0x61, 0x74, 0x65, 0x12, 0x28, 0x0a, 0x0f,
	0x67, 0x72, 0x61, 0x63, 0x65, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x44, 0x61, 0x79, 0x73, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x67, 0x72, 0x61, 0x63, 0x65, 0x50, 0x65, 0x72, 0x69,
	0x6f, 0x64, 0x44, 0x61, 0x79, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x6f, 0x76, 0x65, 0x72, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x46, 0x65, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x6f, 0x76,
	0x65, 0x72, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x46, 0x65, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x61,
	0x74, 0x65, 0x46, 0x65, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x6c, 0x61, 0x74,
	0x65, 0x46, 0x65, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x42, 0x90,
	0x01, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x72, 0x64, 0x61, 0x6f, 0x73, 0x2e, 0x6c, 0x6f,
	0x61, 0x6e, 0x42, 0x17, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x17, 0x61,
	0x72, 0x64, 0x61, 0x2d, 0x6f, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x72, 0x64, 0x61, 0x6f,
	0x73, 0x2f, 0x6c, 0x6f, 0x61, 0x6e, 0xa2, 0x02, 0x03, 0x41, 0x4c, 0x58, 0xaa, 0x02, 0x0b, 0x41,
	0x72, 0x64, 0x61, 0x6f, 0x73, 0x2e, 0x4c, 0x6f, 0x61, 0x6e, 0xca, 0x02, 0x0b, 0x41, 0x72, 0x64,
	0x61, 0x6f, 0x73, 0x5c, 0x4c, 0x6f, 0x61, 0x6e, 0xe2, 0x02, 0x17, 0x41, 0x72, 0x64, 0x61, 0x6f,
	0x73, 0x5c, 0x4c, 0x6f, 0x61, 0x6e, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0xea, 0x02, 0x0c, 0x41, 0x72, 0x64, 0x61, 0x6f, 0x73, 0x3a, 0x3a, 0x4c, 0x6f, 0x61,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ardaos_loan_credit_card_metadata_proto_rawDescOnce sync.Once
	file_ardaos_loan_credit_card_metadata_proto_rawDescData = file_ardaos_loan_credit_card_metadata_proto_rawDesc
)

func file_ardaos_loan_credit_card_metadata_proto_rawDescGZIP() []byte {
	file_ardaos_loan_credit_card_metadata_proto_rawDescOnce.Do(func() {
		file_ardaos_loan_credit_card_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_ardaos_loan_credit_card_metadata_proto_rawDescData)
	})
	return file_ardaos_loan_credit_card_metadata_proto_rawDescData
}

var file_ardaos_loan_credit_card_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ardaos_loan_credit_card_metadata_proto_goTypes = []interface{}{
	(*CreditCardMetadata)(nil), // 0: ardaos.loan.CreditCardMetadata
}
var file_ardaos_loan_credit_card_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ardaos_loan_credit_card_metadata_proto_init() }
func file_ardaos_loan_credit_card_metadata_proto_init() {
	if File_ardaos_loan_credit_card_metadata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ardaos_loan_credit_card_metadata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreditCardMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ardaos_loan_credit_card_metadata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ardaos_loan_credit_card_metadata_proto_goTypes,
		DependencyIndexes: file_ardaos_loan_credit_card_metadata_proto_depIdxs,
		MessageInfos:      file_ardaos_loan_credit_card_metadata_proto_msgTypes,
	}.Build()
	File_ardaos_loan_credit_card_metadata_proto = out.File
	file_ardaos_loan_credit_card_metadata_proto_rawDesc = nil
	file_ardaos_loan_credit_card_metadata_proto_goTypes = nil
	file_ardaos_loan_credit_card_metadata_proto_depIdxs = nil
}
