// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package loan

import (
	fmt "fmt"
	io "io"
	reflect "reflect"
	sync "sync"

	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

var (
	md_InstallmentMetadata                   protoreflect.MessageDescriptor
	fd_InstallmentMetadata_index             protoreflect.FieldDescriptor
	fd_InstallmentMetadata_loanId            protoreflect.FieldDescriptor
	fd_InstallmentMetadata_paymentAmount     protoreflect.FieldDescriptor
	fd_InstallmentMetadata_paymentFrequency  protoreflect.FieldDescriptor
	fd_InstallmentMetadata_remainingPayments protoreflect.FieldDescriptor
	fd_InstallmentMetadata_amortizationType  protoreflect.FieldDescriptor
	fd_InstallmentMetadata_prepaymentAllowed protoreflect.FieldDescriptor
	fd_InstallmentMetadata_creator           protoreflect.FieldDescriptor
)

func init() {
	file_ardaos_loan_installment_metadata_proto_init()
	md_InstallmentMetadata = File_ardaos_loan_installment_metadata_proto.Messages().ByName("InstallmentMetadata")
	fd_InstallmentMetadata_index = md_InstallmentMetadata.Fields().ByName("index")
	fd_InstallmentMetadata_loanId = md_InstallmentMetadata.Fields().ByName("loanId")
	fd_InstallmentMetadata_paymentAmount = md_InstallmentMetadata.Fields().ByName("paymentAmount")
	fd_InstallmentMetadata_paymentFrequency = md_InstallmentMetadata.Fields().ByName("paymentFrequency")
	fd_InstallmentMetadata_remainingPayments = md_InstallmentMetadata.Fields().ByName("remainingPayments")
	fd_InstallmentMetadata_amortizationType = md_InstallmentMetadata.Fields().ByName("amortizationType")
	fd_InstallmentMetadata_prepaymentAllowed = md_InstallmentMetadata.Fields().ByName("prepaymentAllowed")
	fd_InstallmentMetadata_creator = md_InstallmentMetadata.Fields().ByName("creator")
}

var _ protoreflect.Message = (*fastReflection_InstallmentMetadata)(nil)

type fastReflection_InstallmentMetadata InstallmentMetadata

func (x *InstallmentMetadata) ProtoReflect() protoreflect.Message {
	return (*fastReflection_InstallmentMetadata)(x)
}

func (x *InstallmentMetadata) slowProtoReflect() protoreflect.Message {
	mi := &file_ardaos_loan_installment_metadata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_InstallmentMetadata_messageType fastReflection_InstallmentMetadata_messageType
var _ protoreflect.MessageType = fastReflection_InstallmentMetadata_messageType{}

type fastReflection_InstallmentMetadata_messageType struct{}

func (x fastReflection_InstallmentMetadata_messageType) Zero() protoreflect.Message {
	return (*fastReflection_InstallmentMetadata)(nil)
}
func (x fastReflection_InstallmentMetadata_messageType) New() protoreflect.Message {
	return new(fastReflection_InstallmentMetadata)
}
func (x fastReflection_InstallmentMetadata_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_InstallmentMetadata
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_InstallmentMetadata) Descriptor() protoreflect.MessageDescriptor {
	return md_InstallmentMetadata
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_InstallmentMetadata) Type() protoreflect.MessageType {
	return _fastReflection_InstallmentMetadata_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_InstallmentMetadata) New() protoreflect.Message {
	return new(fastReflection_InstallmentMetadata)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_InstallmentMetadata) Interface() protoreflect.ProtoMessage {
	return (*InstallmentMetadata)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_InstallmentMetadata) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Index != "" {
		value := protoreflect.ValueOfString(x.Index)
		if !f(fd_InstallmentMetadata_index, value) {
			return
		}
	}
	if x.LoanId != "" {
		value := protoreflect.ValueOfString(x.LoanId)
		if !f(fd_InstallmentMetadata_loanId, value) {
			return
		}
	}
	if x.PaymentAmount != uint64(0) {
		value := protoreflect.ValueOfUint64(x.PaymentAmount)
		if !f(fd_InstallmentMetadata_paymentAmount, value) {
			return
		}
	}
	if x.PaymentFrequency != "" {
		value := protoreflect.ValueOfString(x.PaymentFrequency)
		if !f(fd_InstallmentMetadata_paymentFrequency, value) {
			return
		}
	}
	if x.RemainingPayments != uint32(0) {
		value := protoreflect.ValueOfUint32(x.RemainingPayments)
		if !f(fd_InstallmentMetadata_remainingPayments, value) {
			return
		}
	}
	if x.AmortizationType != "" {
		value := protoreflect.ValueOfString(x.AmortizationType)
		if !f(fd_InstallmentMetadata_amortizationType, value) {
			return
		}
	}
	if x.PrepaymentAllowed != false {
		value := protoreflect.ValueOfBool(x.PrepaymentAllowed)
		if !f(fd_InstallmentMetadata_prepaymentAllowed, value) {
			return
		}
	}
	if x.Creator != "" {
		value := protoreflect.ValueOfString(x.Creator)
		if !f(fd_InstallmentMetadata_creator, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_InstallmentMetadata) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "ardaos.loan.InstallmentMetadata.index":
		return x.Index != ""
	case "ardaos.loan.InstallmentMetadata.loanId":
		return x.LoanId != ""
	case "ardaos.loan.InstallmentMetadata.paymentAmount":
		return x.PaymentAmount != uint64(0)
	case "ardaos.loan.InstallmentMetadata.paymentFrequency":
		return x.PaymentFrequency != ""
	case "ardaos.loan.InstallmentMetadata.remainingPayments":
		return x.RemainingPayments != uint32(0)
	case "ardaos.loan.InstallmentMetadata.amortizationType":
		return x.AmortizationType != ""
	case "ardaos.loan.InstallmentMetadata.prepaymentAllowed":
		return x.PrepaymentAllowed != false
	case "ardaos.loan.InstallmentMetadata.creator":
		return x.Creator != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ardaos.loan.InstallmentMetadata"))
		}
		panic(fmt.Errorf("message ardaos.loan.InstallmentMetadata does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_InstallmentMetadata) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "ardaos.loan.InstallmentMetadata.index":
		x.Index = ""
	case "ardaos.loan.InstallmentMetadata.loanId":
		x.LoanId = ""
	case "ardaos.loan.InstallmentMetadata.paymentAmount":
		x.PaymentAmount = uint64(0)
	case "ardaos.loan.InstallmentMetadata.paymentFrequency":
		x.PaymentFrequency = ""
	case "ardaos.loan.InstallmentMetadata.remainingPayments":
		x.RemainingPayments = uint32(0)
	case "ardaos.loan.InstallmentMetadata.amortizationType":
		x.AmortizationType = ""
	case "ardaos.loan.InstallmentMetadata.prepaymentAllowed":
		x.PrepaymentAllowed = false
	case "ardaos.loan.InstallmentMetadata.creator":
		x.Creator = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ardaos.loan.InstallmentMetadata"))
		}
		panic(fmt.Errorf("message ardaos.loan.InstallmentMetadata does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_InstallmentMetadata) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "ardaos.loan.InstallmentMetadata.index":
		value := x.Index
		return protoreflect.ValueOfString(value)
	case "ardaos.loan.InstallmentMetadata.loanId":
		value := x.LoanId
		return protoreflect.ValueOfString(value)
	case "ardaos.loan.InstallmentMetadata.paymentAmount":
		value := x.PaymentAmount
		return protoreflect.ValueOfUint64(value)
	case "ardaos.loan.InstallmentMetadata.paymentFrequency":
		value := x.PaymentFrequency
		return protoreflect.ValueOfString(value)
	case "ardaos.loan.InstallmentMetadata.remainingPayments":
		value := x.RemainingPayments
		return protoreflect.ValueOfUint32(value)
	case "ardaos.loan.InstallmentMetadata.amortizationType":
		value := x.AmortizationType
		return protoreflect.ValueOfString(value)
	case "ardaos.loan.InstallmentMetadata.prepaymentAllowed":
		value := x.PrepaymentAllowed
		return protoreflect.ValueOfBool(value)
	case "ardaos.loan.InstallmentMetadata.creator":
		value := x.Creator
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ardaos.loan.InstallmentMetadata"))
		}
		panic(fmt.Errorf("message ardaos.loan.InstallmentMetadata does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_InstallmentMetadata) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "ardaos.loan.InstallmentMetadata.index":
		x.Index = value.Interface().(string)
	case "ardaos.loan.InstallmentMetadata.loanId":
		x.LoanId = value.Interface().(string)
	case "ardaos.loan.InstallmentMetadata.paymentAmount":
		x.PaymentAmount = value.Uint()
	case "ardaos.loan.InstallmentMetadata.paymentFrequency":
		x.PaymentFrequency = value.Interface().(string)
	case "ardaos.loan.InstallmentMetadata.remainingPayments":
		x.RemainingPayments = uint32(value.Uint())
	case "ardaos.loan.InstallmentMetadata.amortizationType":
		x.AmortizationType = value.Interface().(string)
	case "ardaos.loan.InstallmentMetadata.prepaymentAllowed":
		x.PrepaymentAllowed = value.Bool()
	case "ardaos.loan.InstallmentMetadata.creator":
		x.Creator = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ardaos.loan.InstallmentMetadata"))
		}
		panic(fmt.Errorf("message ardaos.loan.InstallmentMetadata does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_InstallmentMetadata) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "ardaos.loan.InstallmentMetadata.index":
		panic(fmt.Errorf("field index of message ardaos.loan.InstallmentMetadata is not mutable"))
	case "ardaos.loan.InstallmentMetadata.loanId":
		panic(fmt.Errorf("field loanId of message ardaos.loan.InstallmentMetadata is not mutable"))
	case "ardaos.loan.InstallmentMetadata.paymentAmount":
		panic(fmt.Errorf("field paymentAmount of message ardaos.loan.InstallmentMetadata is not mutable"))
	case "ardaos.loan.InstallmentMetadata.paymentFrequency":
		panic(fmt.Errorf("field paymentFrequency of message ardaos.loan.InstallmentMetadata is not mutable"))
	case "ardaos.loan.InstallmentMetadata.remainingPayments":
		panic(fmt.Errorf("field remainingPayments of message ardaos.loan.InstallmentMetadata is not mutable"))
	case "ardaos.loan.InstallmentMetadata.amortizationType":
		panic(fmt.Errorf("field amortizationType of message ardaos.loan.InstallmentMetadata is not mutable"))
	case "ardaos.loan.InstallmentMetadata.prepaymentAllowed":
		panic(fmt.Errorf("field prepaymentAllowed of message ardaos.loan.InstallmentMetadata is not mutable"))
	case "ardaos.loan.InstallmentMetadata.creator":
		panic(fmt.Errorf("field creator of message ardaos.loan.InstallmentMetadata is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ardaos.loan.InstallmentMetadata"))
		}
		panic(fmt.Errorf("message ardaos.loan.InstallmentMetadata does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_InstallmentMetadata) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "ardaos.loan.InstallmentMetadata.index":
		return protoreflect.ValueOfString("")
	case "ardaos.loan.InstallmentMetadata.loanId":
		return protoreflect.ValueOfString("")
	case "ardaos.loan.InstallmentMetadata.paymentAmount":
		return protoreflect.ValueOfUint64(uint64(0))
	case "ardaos.loan.InstallmentMetadata.paymentFrequency":
		return protoreflect.ValueOfString("")
	case "ardaos.loan.InstallmentMetadata.remainingPayments":
		return protoreflect.ValueOfUint32(uint32(0))
	case "ardaos.loan.InstallmentMetadata.amortizationType":
		return protoreflect.ValueOfString("")
	case "ardaos.loan.InstallmentMetadata.prepaymentAllowed":
		return protoreflect.ValueOfBool(false)
	case "ardaos.loan.InstallmentMetadata.creator":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ardaos.loan.InstallmentMetadata"))
		}
		panic(fmt.Errorf("message ardaos.loan.InstallmentMetadata does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_InstallmentMetadata) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in ardaos.loan.InstallmentMetadata", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_InstallmentMetadata) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_InstallmentMetadata) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_InstallmentMetadata) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_InstallmentMetadata) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*InstallmentMetadata)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Index)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.LoanId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.PaymentAmount != 0 {
			n += 1 + runtime.Sov(uint64(x.PaymentAmount))
		}
		l = len(x.PaymentFrequency)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.RemainingPayments != 0 {
			n += 1 + runtime.Sov(uint64(x.RemainingPayments))
		}
		l = len(x.AmortizationType)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.PrepaymentAllowed {
			n += 2
		}
		l = len(x.Creator)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*InstallmentMetadata)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Creator) > 0 {
			i -= len(x.Creator)
			copy(dAtA[i:], x.Creator)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Creator)))
			i--
			dAtA[i] = 0x42
		}
		if x.PrepaymentAllowed {
			i--
			if x.PrepaymentAllowed {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x38
		}
		if len(x.AmortizationType) > 0 {
			i -= len(x.AmortizationType)
			copy(dAtA[i:], x.AmortizationType)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.AmortizationType)))
			i--
			dAtA[i] = 0x32
		}
		if x.RemainingPayments != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.RemainingPayments))
			i--
			dAtA[i] = 0x28
		}
		if len(x.PaymentFrequency) > 0 {
			i -= len(x.PaymentFrequency)
			copy(dAtA[i:], x.PaymentFrequency)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.PaymentFrequency)))
			i--
			dAtA[i] = 0x22
		}
		if x.PaymentAmount != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.PaymentAmount))
			i--
			dAtA[i] = 0x18
		}
		if len(x.LoanId) > 0 {
			i -= len(x.LoanId)
			copy(dAtA[i:], x.LoanId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.LoanId)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Index) > 0 {
			i -= len(x.Index)
			copy(dAtA[i:], x.Index)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Index)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*InstallmentMetadata)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: InstallmentMetadata: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: InstallmentMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Index = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field LoanId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.LoanId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field PaymentAmount", wireType)
				}
				x.PaymentAmount = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.PaymentAmount |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field PaymentFrequency", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.PaymentFrequency = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field RemainingPayments", wireType)
				}
				x.RemainingPayments = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.RemainingPayments |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field AmortizationType", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.AmortizationType = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 7:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field PrepaymentAllowed", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.PrepaymentAllowed = bool(v != 0)
			case 8:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Creator = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: ardaos/loan/installment_metadata.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstallmentMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index             string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	LoanId            string `protobuf:"bytes,2,opt,name=loanId,proto3" json:"loanId,omitempty"`
	PaymentAmount     uint64 `protobuf:"varint,3,opt,name=paymentAmount,proto3" json:"paymentAmount,omitempty"`
	PaymentFrequency  string `protobuf:"bytes,4,opt,name=paymentFrequency,proto3" json:"paymentFrequency,omitempty"`
	RemainingPayments uint32 `protobuf:"varint,5,opt,name=remainingPayments,proto3" json:"remainingPayments,omitempty"`
	AmortizationType  string `protobuf:"bytes,6,opt,name=amortizationType,proto3" json:"amortizationType,omitempty"`
	PrepaymentAllowed bool   `protobuf:"varint,7,opt,name=prepaymentAllowed,proto3" json:"prepaymentAllowed,omitempty"`
	Creator           string `protobuf:"bytes,8,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (x *InstallmentMetadata) Reset() {
	*x = InstallmentMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ardaos_loan_installment_metadata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstallmentMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallmentMetadata) ProtoMessage() {}

// Deprecated: Use InstallmentMetadata.ProtoReflect.Descriptor instead.
func (*InstallmentMetadata) Descriptor() ([]byte, []int) {
	return file_ardaos_loan_installment_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *InstallmentMetadata) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *InstallmentMetadata) GetLoanId() string {
	if x != nil {
		return x.LoanId
	}
	return ""
}

func (x *InstallmentMetadata) GetPaymentAmount() uint64 {
	if x != nil {
		return x.PaymentAmount
	}
	return 0
}

func (x *InstallmentMetadata) GetPaymentFrequency() string {
	if x != nil {
		return x.PaymentFrequency
	}
	return ""
}

func (x *InstallmentMetadata) GetRemainingPayments() uint32 {
	if x != nil {
		return x.RemainingPayments
	}
	return 0
}

func (x *InstallmentMetadata) GetAmortizationType() string {
	if x != nil {
		return x.AmortizationType
	}
	return ""
}

func (x *InstallmentMetadata) GetPrepaymentAllowed() bool {
	if x != nil {
		return x.PrepaymentAllowed
	}
	return false
}

func (x *InstallmentMetadata) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

var File_ardaos_loan_installment_metadata_proto protoreflect.FileDescriptor

var file_ardaos_loan_installment_metadata_proto_rawDesc = []byte{
	0x0a, 0x26, 0x61, 0x72, 0x64, 0x61, 0x6f, 0x73, 0x2f, 0x6c, 0x6f, 0x61, 0x6e, 0x2f, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x72, 0x64, 0x61, 0x6f, 0x73,
	0x2e, 0x6c, 0x6f, 0x61, 0x6e, 0x22, 0xb7, 0x02, 0x0a, 0x13, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c,
	0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x61, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x6f, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0d, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x2a, 0x0a, 0x10, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x46, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x2c, 0x0a,
	0x11, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x11, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e,
	0x69, 0x6e, 0x67, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x2a, 0x0a, 0x10, 0x61,
	0x6d, 0x6f, 0x72, 0x74, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x61, 0x6d, 0x6f, 0x72, 0x74, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x70, 0x72, 0x65, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x11, 0x70, 0x72, 0x65, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x6c,
	0x6c, 0x6f, 0x77, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x42,
	0x91, 0x01, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x72, 0x64, 0x61, 0x6f, 0x73, 0x2e, 0x6c,
	0x6f, 0x61, 0x6e, 0x42, 0x18, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x17, 0x61, 0x72, 0x64, 0x61, 0x2d, 0x6f, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x72, 0x64,
	0x61, 0x6f, 0x73, 0x2f, 0x6c, 0x6f, 0x61, 0x6e, 0xa2, 0x02, 0x03, 0x41, 0x4c, 0x58, 0xaa, 0x02,
	0x0b, 0x41, 0x72, 0x64, 0x61, 0x6f, 0x73, 0x2e, 0x4c, 0x6f, 0x61, 0x6e, 0xca, 0x02, 0x0b, 0x41,
	0x72, 0x64, 0x61, 0x6f, 0x73, 0x5c, 0x4c, 0x6f, 0x61, 0x6e, 0xe2, 0x02, 0x17, 0x41, 0x72, 0x64,
	0x61, 0x6f, 0x73, 0x5c, 0x4c, 0x6f, 0x61, 0x6e, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0c, 0x41, 0x72, 0x64, 0x61, 0x6f, 0x73, 0x3a, 0x3a, 0x4c,
	0x6f, 0x61, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ardaos_loan_installment_metadata_proto_rawDescOnce sync.Once
	file_ardaos_loan_installment_metadata_proto_rawDescData = file_ardaos_loan_installment_metadata_proto_rawDesc
)

func file_ardaos_loan_installment_metadata_proto_rawDescGZIP() []byte {
	file_ardaos_loan_installment_metadata_proto_rawDescOnce.Do(func() {
		file_ardaos_loan_installment_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_ardaos_loan_installment_metadata_proto_rawDescData)
	})
	return file_ardaos_loan_installment_metadata_proto_rawDescData
}

var file_ardaos_loan_installment_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ardaos_loan_installment_metadata_proto_goTypes = []interface{}{
	(*InstallmentMetadata)(nil), // 0: ardaos.loan.InstallmentMetadata
}
var file_ardaos_loan_installment_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ardaos_loan_installment_metadata_proto_init() }
func file_ardaos_loan_installment_metadata_proto_init() {
	if File_ardaos_loan_installment_metadata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ardaos_loan_installment_metadata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstallmentMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ardaos_loan_installment_metadata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ardaos_loan_installment_metadata_proto_goTypes,
		DependencyIndexes: file_ardaos_loan_installment_metadata_proto_depIdxs,
		MessageInfos:      file_ardaos_loan_installment_metadata_proto_msgTypes,
	}.Build()
	File_ardaos_loan_installment_metadata_proto = out.File
	file_ardaos_loan_installment_metadata_proto_rawDesc = nil
	file_ardaos_loan_installment_metadata_proto_goTypes = nil
	file_ardaos_loan_installment_metadata_proto_depIdxs = nil
}
