// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package loan

import (
	fmt "fmt"
	io "io"
	reflect "reflect"
	sync "sync"

	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

var (
	md_LoanState                 protoreflect.MessageDescriptor
	fd_LoanState_index           protoreflect.FieldDescriptor
	fd_LoanState_loanId          protoreflect.FieldDescriptor
	fd_LoanState_status          protoreflect.FieldDescriptor
	fd_LoanState_currentBalance  protoreflect.FieldDescriptor
	fd_LoanState_paymentsMade    protoreflect.FieldDescriptor
	fd_LoanState_lastPaymentDate protoreflect.FieldDescriptor
	fd_LoanState_nextPaymentDate protoreflect.FieldDescriptor
	fd_LoanState_delinquencyDays protoreflect.FieldDescriptor
	fd_LoanState_creator         protoreflect.FieldDescriptor
)

func init() {
	file_ardaos_loan_loan_state_proto_init()
	md_LoanState = File_ardaos_loan_loan_state_proto.Messages().ByName("LoanState")
	fd_LoanState_index = md_LoanState.Fields().ByName("index")
	fd_LoanState_loanId = md_LoanState.Fields().ByName("loanId")
	fd_LoanState_status = md_LoanState.Fields().ByName("status")
	fd_LoanState_currentBalance = md_LoanState.Fields().ByName("currentBalance")
	fd_LoanState_paymentsMade = md_LoanState.Fields().ByName("paymentsMade")
	fd_LoanState_lastPaymentDate = md_LoanState.Fields().ByName("lastPaymentDate")
	fd_LoanState_nextPaymentDate = md_LoanState.Fields().ByName("nextPaymentDate")
	fd_LoanState_delinquencyDays = md_LoanState.Fields().ByName("delinquencyDays")
	fd_LoanState_creator = md_LoanState.Fields().ByName("creator")
}

var _ protoreflect.Message = (*fastReflection_LoanState)(nil)

type fastReflection_LoanState LoanState

func (x *LoanState) ProtoReflect() protoreflect.Message {
	return (*fastReflection_LoanState)(x)
}

func (x *LoanState) slowProtoReflect() protoreflect.Message {
	mi := &file_ardaos_loan_loan_state_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_LoanState_messageType fastReflection_LoanState_messageType
var _ protoreflect.MessageType = fastReflection_LoanState_messageType{}

type fastReflection_LoanState_messageType struct{}

func (x fastReflection_LoanState_messageType) Zero() protoreflect.Message {
	return (*fastReflection_LoanState)(nil)
}
func (x fastReflection_LoanState_messageType) New() protoreflect.Message {
	return new(fastReflection_LoanState)
}
func (x fastReflection_LoanState_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_LoanState
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_LoanState) Descriptor() protoreflect.MessageDescriptor {
	return md_LoanState
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_LoanState) Type() protoreflect.MessageType {
	return _fastReflection_LoanState_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_LoanState) New() protoreflect.Message {
	return new(fastReflection_LoanState)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_LoanState) Interface() protoreflect.ProtoMessage {
	return (*LoanState)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_LoanState) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Index != "" {
		value := protoreflect.ValueOfString(x.Index)
		if !f(fd_LoanState_index, value) {
			return
		}
	}
	if x.LoanId != "" {
		value := protoreflect.ValueOfString(x.LoanId)
		if !f(fd_LoanState_loanId, value) {
			return
		}
	}
	if x.Status != "" {
		value := protoreflect.ValueOfString(x.Status)
		if !f(fd_LoanState_status, value) {
			return
		}
	}
	if x.CurrentBalance != uint64(0) {
		value := protoreflect.ValueOfUint64(x.CurrentBalance)
		if !f(fd_LoanState_currentBalance, value) {
			return
		}
	}
	if x.PaymentsMade != uint32(0) {
		value := protoreflect.ValueOfUint32(x.PaymentsMade)
		if !f(fd_LoanState_paymentsMade, value) {
			return
		}
	}
	if x.LastPaymentDate != "" {
		value := protoreflect.ValueOfString(x.LastPaymentDate)
		if !f(fd_LoanState_lastPaymentDate, value) {
			return
		}
	}
	if x.NextPaymentDate != "" {
		value := protoreflect.ValueOfString(x.NextPaymentDate)
		if !f(fd_LoanState_nextPaymentDate, value) {
			return
		}
	}
	if x.DelinquencyDays != uint32(0) {
		value := protoreflect.ValueOfUint32(x.DelinquencyDays)
		if !f(fd_LoanState_delinquencyDays, value) {
			return
		}
	}
	if x.Creator != "" {
		value := protoreflect.ValueOfString(x.Creator)
		if !f(fd_LoanState_creator, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_LoanState) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "ardaos.loan.LoanState.index":
		return x.Index != ""
	case "ardaos.loan.LoanState.loanId":
		return x.LoanId != ""
	case "ardaos.loan.LoanState.status":
		return x.Status != ""
	case "ardaos.loan.LoanState.currentBalance":
		return x.CurrentBalance != uint64(0)
	case "ardaos.loan.LoanState.paymentsMade":
		return x.PaymentsMade != uint32(0)
	case "ardaos.loan.LoanState.lastPaymentDate":
		return x.LastPaymentDate != ""
	case "ardaos.loan.LoanState.nextPaymentDate":
		return x.NextPaymentDate != ""
	case "ardaos.loan.LoanState.delinquencyDays":
		return x.DelinquencyDays != uint32(0)
	case "ardaos.loan.LoanState.creator":
		return x.Creator != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ardaos.loan.LoanState"))
		}
		panic(fmt.Errorf("message ardaos.loan.LoanState does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_LoanState) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "ardaos.loan.LoanState.index":
		x.Index = ""
	case "ardaos.loan.LoanState.loanId":
		x.LoanId = ""
	case "ardaos.loan.LoanState.status":
		x.Status = ""
	case "ardaos.loan.LoanState.currentBalance":
		x.CurrentBalance = uint64(0)
	case "ardaos.loan.LoanState.paymentsMade":
		x.PaymentsMade = uint32(0)
	case "ardaos.loan.LoanState.lastPaymentDate":
		x.LastPaymentDate = ""
	case "ardaos.loan.LoanState.nextPaymentDate":
		x.NextPaymentDate = ""
	case "ardaos.loan.LoanState.delinquencyDays":
		x.DelinquencyDays = uint32(0)
	case "ardaos.loan.LoanState.creator":
		x.Creator = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ardaos.loan.LoanState"))
		}
		panic(fmt.Errorf("message ardaos.loan.LoanState does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_LoanState) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "ardaos.loan.LoanState.index":
		value := x.Index
		return protoreflect.ValueOfString(value)
	case "ardaos.loan.LoanState.loanId":
		value := x.LoanId
		return protoreflect.ValueOfString(value)
	case "ardaos.loan.LoanState.status":
		value := x.Status
		return protoreflect.ValueOfString(value)
	case "ardaos.loan.LoanState.currentBalance":
		value := x.CurrentBalance
		return protoreflect.ValueOfUint64(value)
	case "ardaos.loan.LoanState.paymentsMade":
		value := x.PaymentsMade
		return protoreflect.ValueOfUint32(value)
	case "ardaos.loan.LoanState.lastPaymentDate":
		value := x.LastPaymentDate
		return protoreflect.ValueOfString(value)
	case "ardaos.loan.LoanState.nextPaymentDate":
		value := x.NextPaymentDate
		return protoreflect.ValueOfString(value)
	case "ardaos.loan.LoanState.delinquencyDays":
		value := x.DelinquencyDays
		return protoreflect.ValueOfUint32(value)
	case "ardaos.loan.LoanState.creator":
		value := x.Creator
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ardaos.loan.LoanState"))
		}
		panic(fmt.Errorf("message ardaos.loan.LoanState does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_LoanState) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "ardaos.loan.LoanState.index":
		x.Index = value.Interface().(string)
	case "ardaos.loan.LoanState.loanId":
		x.LoanId = value.Interface().(string)
	case "ardaos.loan.LoanState.status":
		x.Status = value.Interface().(string)
	case "ardaos.loan.LoanState.currentBalance":
		x.CurrentBalance = value.Uint()
	case "ardaos.loan.LoanState.paymentsMade":
		x.PaymentsMade = uint32(value.Uint())
	case "ardaos.loan.LoanState.lastPaymentDate":
		x.LastPaymentDate = value.Interface().(string)
	case "ardaos.loan.LoanState.nextPaymentDate":
		x.NextPaymentDate = value.Interface().(string)
	case "ardaos.loan.LoanState.delinquencyDays":
		x.DelinquencyDays = uint32(value.Uint())
	case "ardaos.loan.LoanState.creator":
		x.Creator = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ardaos.loan.LoanState"))
		}
		panic(fmt.Errorf("message ardaos.loan.LoanState does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_LoanState) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "ardaos.loan.LoanState.index":
		panic(fmt.Errorf("field index of message ardaos.loan.LoanState is not mutable"))
	case "ardaos.loan.LoanState.loanId":
		panic(fmt.Errorf("field loanId of message ardaos.loan.LoanState is not mutable"))
	case "ardaos.loan.LoanState.status":
		panic(fmt.Errorf("field status of message ardaos.loan.LoanState is not mutable"))
	case "ardaos.loan.LoanState.currentBalance":
		panic(fmt.Errorf("field currentBalance of message ardaos.loan.LoanState is not mutable"))
	case "ardaos.loan.LoanState.paymentsMade":
		panic(fmt.Errorf("field paymentsMade of message ardaos.loan.LoanState is not mutable"))
	case "ardaos.loan.LoanState.lastPaymentDate":
		panic(fmt.Errorf("field lastPaymentDate of message ardaos.loan.LoanState is not mutable"))
	case "ardaos.loan.LoanState.nextPaymentDate":
		panic(fmt.Errorf("field nextPaymentDate of message ardaos.loan.LoanState is not mutable"))
	case "ardaos.loan.LoanState.delinquencyDays":
		panic(fmt.Errorf("field delinquencyDays of message ardaos.loan.LoanState is not mutable"))
	case "ardaos.loan.LoanState.creator":
		panic(fmt.Errorf("field creator of message ardaos.loan.LoanState is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ardaos.loan.LoanState"))
		}
		panic(fmt.Errorf("message ardaos.loan.LoanState does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_LoanState) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "ardaos.loan.LoanState.index":
		return protoreflect.ValueOfString("")
	case "ardaos.loan.LoanState.loanId":
		return protoreflect.ValueOfString("")
	case "ardaos.loan.LoanState.status":
		return protoreflect.ValueOfString("")
	case "ardaos.loan.LoanState.currentBalance":
		return protoreflect.ValueOfUint64(uint64(0))
	case "ardaos.loan.LoanState.paymentsMade":
		return protoreflect.ValueOfUint32(uint32(0))
	case "ardaos.loan.LoanState.lastPaymentDate":
		return protoreflect.ValueOfString("")
	case "ardaos.loan.LoanState.nextPaymentDate":
		return protoreflect.ValueOfString("")
	case "ardaos.loan.LoanState.delinquencyDays":
		return protoreflect.ValueOfUint32(uint32(0))
	case "ardaos.loan.LoanState.creator":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ardaos.loan.LoanState"))
		}
		panic(fmt.Errorf("message ardaos.loan.LoanState does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_LoanState) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in ardaos.loan.LoanState", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_LoanState) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_LoanState) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_LoanState) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_LoanState) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*LoanState)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Index)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.LoanId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Status)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.CurrentBalance != 0 {
			n += 1 + runtime.Sov(uint64(x.CurrentBalance))
		}
		if x.PaymentsMade != 0 {
			n += 1 + runtime.Sov(uint64(x.PaymentsMade))
		}
		l = len(x.LastPaymentDate)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.NextPaymentDate)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.DelinquencyDays != 0 {
			n += 1 + runtime.Sov(uint64(x.DelinquencyDays))
		}
		l = len(x.Creator)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*LoanState)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Creator) > 0 {
			i -= len(x.Creator)
			copy(dAtA[i:], x.Creator)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Creator)))
			i--
			dAtA[i] = 0x4a
		}
		if x.DelinquencyDays != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.DelinquencyDays))
			i--
			dAtA[i] = 0x40
		}
		if len(x.NextPaymentDate) > 0 {
			i -= len(x.NextPaymentDate)
			copy(dAtA[i:], x.NextPaymentDate)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.NextPaymentDate)))
			i--
			dAtA[i] = 0x3a
		}
		if len(x.LastPaymentDate) > 0 {
			i -= len(x.LastPaymentDate)
			copy(dAtA[i:], x.LastPaymentDate)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.LastPaymentDate)))
			i--
			dAtA[i] = 0x32
		}
		if x.PaymentsMade != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.PaymentsMade))
			i--
			dAtA[i] = 0x28
		}
		if x.CurrentBalance != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.CurrentBalance))
			i--
			dAtA[i] = 0x20
		}
		if len(x.Status) > 0 {
			i -= len(x.Status)
			copy(dAtA[i:], x.Status)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Status)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.LoanId) > 0 {
			i -= len(x.LoanId)
			copy(dAtA[i:], x.LoanId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.LoanId)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Index) > 0 {
			i -= len(x.Index)
			copy(dAtA[i:], x.Index)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Index)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*LoanState)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: LoanState: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: LoanState: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Index = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field LoanId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.LoanId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Status = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field CurrentBalance", wireType)
				}
				x.CurrentBalance = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.CurrentBalance |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 5:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field PaymentsMade", wireType)
				}
				x.PaymentsMade = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.PaymentsMade |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field LastPaymentDate", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.LastPaymentDate = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 7:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field NextPaymentDate", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.NextPaymentDate = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 8:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field DelinquencyDays", wireType)
				}
				x.DelinquencyDays = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.DelinquencyDays |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 9:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Creator = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: ardaos/loan/loan_state.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoanState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index           string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	LoanId          string `protobuf:"bytes,2,opt,name=loanId,proto3" json:"loanId,omitempty"`
	Status          string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CurrentBalance  uint64 `protobuf:"varint,4,opt,name=currentBalance,proto3" json:"currentBalance,omitempty"`
	PaymentsMade    uint32 `protobuf:"varint,5,opt,name=paymentsMade,proto3" json:"paymentsMade,omitempty"`
	LastPaymentDate string `protobuf:"bytes,6,opt,name=lastPaymentDate,proto3" json:"lastPaymentDate,omitempty"`
	NextPaymentDate string `protobuf:"bytes,7,opt,name=nextPaymentDate,proto3" json:"nextPaymentDate,omitempty"`
	DelinquencyDays uint32 `protobuf:"varint,8,opt,name=delinquencyDays,proto3" json:"delinquencyDays,omitempty"`
	Creator         string `protobuf:"bytes,9,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (x *LoanState) Reset() {
	*x = LoanState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ardaos_loan_loan_state_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoanState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanState) ProtoMessage() {}

// Deprecated: Use LoanState.ProtoReflect.Descriptor instead.
func (*LoanState) Descriptor() ([]byte, []int) {
	return file_ardaos_loan_loan_state_proto_rawDescGZIP(), []int{0}
}

func (x *LoanState) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *LoanState) GetLoanId() string {
	if x != nil {
		return x.LoanId
	}
	return ""
}

func (x *LoanState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LoanState) GetCurrentBalance() uint64 {
	if x != nil {
		return x.CurrentBalance
	}
	return 0
}

func (x *LoanState) GetPaymentsMade() uint32 {
	if x != nil {
		return x.PaymentsMade
	}
	return 0
}

func (x *LoanState) GetLastPaymentDate() string {
	if x != nil {
		return x.LastPaymentDate
	}
	return ""
}

func (x *LoanState) GetNextPaymentDate() string {
	if x != nil {
		return x.NextPaymentDate
	}
	return ""
}

func (x *LoanState) GetDelinquencyDays() uint32 {
	if x != nil {
		return x.DelinquencyDays
	}
	return 0
}

func (x *LoanState) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

var File_ardaos_loan_loan_state_proto protoreflect.FileDescriptor

var file_ardaos_loan_loan_state_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x72, 0x64, 0x61, 0x6f, 0x73, 0x2f, 0x6c, 0x6f, 0x61, 0x6e, 0x2f, 0x6c, 0x6f,
	0x61, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b,
	0x61, 0x72, 0x64, 0x61, 0x6f, 0x73, 0x2e, 0x6c, 0x6f, 0x61, 0x6e, 0x22, 0xb5, 0x02, 0x0a, 0x09,
	0x4c, 0x6f, 0x61, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x61, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6c, 0x6f, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x26, 0x0a, 0x0e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x4d, 0x61, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x4d, 0x61, 0x64, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x6c,
	0x61, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x6e, 0x65, 0x78, 0x74, 0x50, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x6e, 0x65, 0x78, 0x74, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12,
	0x28, 0x0a, 0x0f, 0x64, 0x65, 0x6c, 0x69, 0x6e, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x44, 0x61,
	0x79, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x64, 0x65, 0x6c, 0x69, 0x6e, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x79, 0x44, 0x61, 0x79, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x6f, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x6f, 0x72, 0x42, 0x87, 0x01, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x72, 0x64, 0x61,
	0x6f, 0x73, 0x2e, 0x6c, 0x6f, 0x61, 0x6e, 0x42, 0x0e, 0x4c, 0x6f, 0x61, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x17, 0x61, 0x72, 0x64, 0x61, 0x2d,
	0x6f, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x72, 0x64, 0x61, 0x6f, 0x73, 0x2f, 0x6c, 0x6f,
	0x61, 0x6e, 0xa2, 0x02, 0x03, 0x41, 0x4c, 0x58, 0xaa, 0x02, 0x0b, 0x41, 0x72, 0x64, 0x61, 0x6f,
	0x73, 0x2e, 0x4c, 0x6f, 0x61, 0x6e, 0xca, 0x02, 0x0b, 0x41, 0x72, 0x64, 0x61, 0x6f, 0x73, 0x5c,
	0x4c, 0x6f, 0x61, 0x6e, 0xe2, 0x02, 0x17, 0x41, 0x72, 0x64, 0x61, 0x6f, 0x73, 0x5c, 0x4c, 0x6f,
	0x61, 0x6e, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02,
	0x0c, 0x41, 0x72, 0x64, 0x61, 0x6f, 0x73, 0x3a, 0x3a, 0x4c, 0x6f, 0x61, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ardaos_loan_loan_state_proto_rawDescOnce sync.Once
	file_ardaos_loan_loan_state_proto_rawDescData = file_ardaos_loan_loan_state_proto_rawDesc
)

func file_ardaos_loan_loan_state_proto_rawDescGZIP() []byte {
	file_ardaos_loan_loan_state_proto_rawDescOnce.Do(func() {
		file_ardaos_loan_loan_state_proto_rawDescData = protoimpl.X.CompressGZIP(file_ardaos_loan_loan_state_proto_rawDescData)
	})
	return file_ardaos_loan_loan_state_proto_rawDescData
}

var file_ardaos_loan_loan_state_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ardaos_loan_loan_state_proto_goTypes = []interface{}{
	(*LoanState)(nil), // 0: ardaos.loan.LoanState
}
var file_ardaos_loan_loan_state_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ardaos_loan_loan_state_proto_init() }
func file_ardaos_loan_loan_state_proto_init() {
	if File_ardaos_loan_loan_state_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ardaos_loan_loan_state_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoanState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ardaos_loan_loan_state_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ardaos_loan_loan_state_proto_goTypes,
		DependencyIndexes: file_ardaos_loan_loan_state_proto_depIdxs,
		MessageInfos:      file_ardaos_loan_loan_state_proto_msgTypes,
	}.Build()
	File_ardaos_loan_loan_state_proto = out.File
	file_ardaos_loan_loan_state_proto_rawDesc = nil
	file_ardaos_loan_loan_state_proto_goTypes = nil
	file_ardaos_loan_loan_state_proto_depIdxs = nil
}
