// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package loan

import (
	fmt "fmt"
	io "io"
	reflect "reflect"
	sync "sync"

	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

var (
	md_McaMetadata                           protoreflect.MessageDescriptor
	fd_McaMetadata_index                     protoreflect.FieldDescriptor
	fd_McaMetadata_loanId                    protoreflect.FieldDescriptor
	fd_McaMetadata_dailyCollectionPercentage protoreflect.FieldDescriptor
	fd_McaMetadata_merchantId                protoreflect.FieldDescriptor
	fd_McaMetadata_processorName             protoreflect.FieldDescriptor
	fd_McaMetadata_estimatedTermDays         protoreflect.FieldDescriptor
	fd_McaMetadata_totalPaybackAmount        protoreflect.FieldDescriptor
	fd_McaMetadata_dailySalesAverage         protoreflect.FieldDescriptor
	fd_McaMetadata_creator                   protoreflect.FieldDescriptor
)

func init() {
	file_ardaos_loan_mca_metadata_proto_init()
	md_McaMetadata = File_ardaos_loan_mca_metadata_proto.Messages().ByName("McaMetadata")
	fd_McaMetadata_index = md_McaMetadata.Fields().ByName("index")
	fd_McaMetadata_loanId = md_McaMetadata.Fields().ByName("loanId")
	fd_McaMetadata_dailyCollectionPercentage = md_McaMetadata.Fields().ByName("dailyCollectionPercentage")
	fd_McaMetadata_merchantId = md_McaMetadata.Fields().ByName("merchantId")
	fd_McaMetadata_processorName = md_McaMetadata.Fields().ByName("processorName")
	fd_McaMetadata_estimatedTermDays = md_McaMetadata.Fields().ByName("estimatedTermDays")
	fd_McaMetadata_totalPaybackAmount = md_McaMetadata.Fields().ByName("totalPaybackAmount")
	fd_McaMetadata_dailySalesAverage = md_McaMetadata.Fields().ByName("dailySalesAverage")
	fd_McaMetadata_creator = md_McaMetadata.Fields().ByName("creator")
}

var _ protoreflect.Message = (*fastReflection_McaMetadata)(nil)

type fastReflection_McaMetadata McaMetadata

func (x *McaMetadata) ProtoReflect() protoreflect.Message {
	return (*fastReflection_McaMetadata)(x)
}

func (x *McaMetadata) slowProtoReflect() protoreflect.Message {
	mi := &file_ardaos_loan_mca_metadata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_McaMetadata_messageType fastReflection_McaMetadata_messageType
var _ protoreflect.MessageType = fastReflection_McaMetadata_messageType{}

type fastReflection_McaMetadata_messageType struct{}

func (x fastReflection_McaMetadata_messageType) Zero() protoreflect.Message {
	return (*fastReflection_McaMetadata)(nil)
}
func (x fastReflection_McaMetadata_messageType) New() protoreflect.Message {
	return new(fastReflection_McaMetadata)
}
func (x fastReflection_McaMetadata_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_McaMetadata
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_McaMetadata) Descriptor() protoreflect.MessageDescriptor {
	return md_McaMetadata
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_McaMetadata) Type() protoreflect.MessageType {
	return _fastReflection_McaMetadata_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_McaMetadata) New() protoreflect.Message {
	return new(fastReflection_McaMetadata)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_McaMetadata) Interface() protoreflect.ProtoMessage {
	return (*McaMetadata)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_McaMetadata) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Index != "" {
		value := protoreflect.ValueOfString(x.Index)
		if !f(fd_McaMetadata_index, value) {
			return
		}
	}
	if x.LoanId != "" {
		value := protoreflect.ValueOfString(x.LoanId)
		if !f(fd_McaMetadata_loanId, value) {
			return
		}
	}
	if x.DailyCollectionPercentage != "" {
		value := protoreflect.ValueOfString(x.DailyCollectionPercentage)
		if !f(fd_McaMetadata_dailyCollectionPercentage, value) {
			return
		}
	}
	if x.MerchantId != "" {
		value := protoreflect.ValueOfString(x.MerchantId)
		if !f(fd_McaMetadata_merchantId, value) {
			return
		}
	}
	if x.ProcessorName != "" {
		value := protoreflect.ValueOfString(x.ProcessorName)
		if !f(fd_McaMetadata_processorName, value) {
			return
		}
	}
	if x.EstimatedTermDays != uint32(0) {
		value := protoreflect.ValueOfUint32(x.EstimatedTermDays)
		if !f(fd_McaMetadata_estimatedTermDays, value) {
			return
		}
	}
	if x.TotalPaybackAmount != uint64(0) {
		value := protoreflect.ValueOfUint64(x.TotalPaybackAmount)
		if !f(fd_McaMetadata_totalPaybackAmount, value) {
			return
		}
	}
	if x.DailySalesAverage != uint64(0) {
		value := protoreflect.ValueOfUint64(x.DailySalesAverage)
		if !f(fd_McaMetadata_dailySalesAverage, value) {
			return
		}
	}
	if x.Creator != "" {
		value := protoreflect.ValueOfString(x.Creator)
		if !f(fd_McaMetadata_creator, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_McaMetadata) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "ardaos.loan.McaMetadata.index":
		return x.Index != ""
	case "ardaos.loan.McaMetadata.loanId":
		return x.LoanId != ""
	case "ardaos.loan.McaMetadata.dailyCollectionPercentage":
		return x.DailyCollectionPercentage != ""
	case "ardaos.loan.McaMetadata.merchantId":
		return x.MerchantId != ""
	case "ardaos.loan.McaMetadata.processorName":
		return x.ProcessorName != ""
	case "ardaos.loan.McaMetadata.estimatedTermDays":
		return x.EstimatedTermDays != uint32(0)
	case "ardaos.loan.McaMetadata.totalPaybackAmount":
		return x.TotalPaybackAmount != uint64(0)
	case "ardaos.loan.McaMetadata.dailySalesAverage":
		return x.DailySalesAverage != uint64(0)
	case "ardaos.loan.McaMetadata.creator":
		return x.Creator != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ardaos.loan.McaMetadata"))
		}
		panic(fmt.Errorf("message ardaos.loan.McaMetadata does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_McaMetadata) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "ardaos.loan.McaMetadata.index":
		x.Index = ""
	case "ardaos.loan.McaMetadata.loanId":
		x.LoanId = ""
	case "ardaos.loan.McaMetadata.dailyCollectionPercentage":
		x.DailyCollectionPercentage = ""
	case "ardaos.loan.McaMetadata.merchantId":
		x.MerchantId = ""
	case "ardaos.loan.McaMetadata.processorName":
		x.ProcessorName = ""
	case "ardaos.loan.McaMetadata.estimatedTermDays":
		x.EstimatedTermDays = uint32(0)
	case "ardaos.loan.McaMetadata.totalPaybackAmount":
		x.TotalPaybackAmount = uint64(0)
	case "ardaos.loan.McaMetadata.dailySalesAverage":
		x.DailySalesAverage = uint64(0)
	case "ardaos.loan.McaMetadata.creator":
		x.Creator = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ardaos.loan.McaMetadata"))
		}
		panic(fmt.Errorf("message ardaos.loan.McaMetadata does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_McaMetadata) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "ardaos.loan.McaMetadata.index":
		value := x.Index
		return protoreflect.ValueOfString(value)
	case "ardaos.loan.McaMetadata.loanId":
		value := x.LoanId
		return protoreflect.ValueOfString(value)
	case "ardaos.loan.McaMetadata.dailyCollectionPercentage":
		value := x.DailyCollectionPercentage
		return protoreflect.ValueOfString(value)
	case "ardaos.loan.McaMetadata.merchantId":
		value := x.MerchantId
		return protoreflect.ValueOfString(value)
	case "ardaos.loan.McaMetadata.processorName":
		value := x.ProcessorName
		return protoreflect.ValueOfString(value)
	case "ardaos.loan.McaMetadata.estimatedTermDays":
		value := x.EstimatedTermDays
		return protoreflect.ValueOfUint32(value)
	case "ardaos.loan.McaMetadata.totalPaybackAmount":
		value := x.TotalPaybackAmount
		return protoreflect.ValueOfUint64(value)
	case "ardaos.loan.McaMetadata.dailySalesAverage":
		value := x.DailySalesAverage
		return protoreflect.ValueOfUint64(value)
	case "ardaos.loan.McaMetadata.creator":
		value := x.Creator
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ardaos.loan.McaMetadata"))
		}
		panic(fmt.Errorf("message ardaos.loan.McaMetadata does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_McaMetadata) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "ardaos.loan.McaMetadata.index":
		x.Index = value.Interface().(string)
	case "ardaos.loan.McaMetadata.loanId":
		x.LoanId = value.Interface().(string)
	case "ardaos.loan.McaMetadata.dailyCollectionPercentage":
		x.DailyCollectionPercentage = value.Interface().(string)
	case "ardaos.loan.McaMetadata.merchantId":
		x.MerchantId = value.Interface().(string)
	case "ardaos.loan.McaMetadata.processorName":
		x.ProcessorName = value.Interface().(string)
	case "ardaos.loan.McaMetadata.estimatedTermDays":
		x.EstimatedTermDays = uint32(value.Uint())
	case "ardaos.loan.McaMetadata.totalPaybackAmount":
		x.TotalPaybackAmount = value.Uint()
	case "ardaos.loan.McaMetadata.dailySalesAverage":
		x.DailySalesAverage = value.Uint()
	case "ardaos.loan.McaMetadata.creator":
		x.Creator = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ardaos.loan.McaMetadata"))
		}
		panic(fmt.Errorf("message ardaos.loan.McaMetadata does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_McaMetadata) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "ardaos.loan.McaMetadata.index":
		panic(fmt.Errorf("field index of message ardaos.loan.McaMetadata is not mutable"))
	case "ardaos.loan.McaMetadata.loanId":
		panic(fmt.Errorf("field loanId of message ardaos.loan.McaMetadata is not mutable"))
	case "ardaos.loan.McaMetadata.dailyCollectionPercentage":
		panic(fmt.Errorf("field dailyCollectionPercentage of message ardaos.loan.McaMetadata is not mutable"))
	case "ardaos.loan.McaMetadata.merchantId":
		panic(fmt.Errorf("field merchantId of message ardaos.loan.McaMetadata is not mutable"))
	case "ardaos.loan.McaMetadata.processorName":
		panic(fmt.Errorf("field processorName of message ardaos.loan.McaMetadata is not mutable"))
	case "ardaos.loan.McaMetadata.estimatedTermDays":
		panic(fmt.Errorf("field estimatedTermDays of message ardaos.loan.McaMetadata is not mutable"))
	case "ardaos.loan.McaMetadata.totalPaybackAmount":
		panic(fmt.Errorf("field totalPaybackAmount of message ardaos.loan.McaMetadata is not mutable"))
	case "ardaos.loan.McaMetadata.dailySalesAverage":
		panic(fmt.Errorf("field dailySalesAverage of message ardaos.loan.McaMetadata is not mutable"))
	case "ardaos.loan.McaMetadata.creator":
		panic(fmt.Errorf("field creator of message ardaos.loan.McaMetadata is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ardaos.loan.McaMetadata"))
		}
		panic(fmt.Errorf("message ardaos.loan.McaMetadata does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_McaMetadata) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "ardaos.loan.McaMetadata.index":
		return protoreflect.ValueOfString("")
	case "ardaos.loan.McaMetadata.loanId":
		return protoreflect.ValueOfString("")
	case "ardaos.loan.McaMetadata.dailyCollectionPercentage":
		return protoreflect.ValueOfString("")
	case "ardaos.loan.McaMetadata.merchantId":
		return protoreflect.ValueOfString("")
	case "ardaos.loan.McaMetadata.processorName":
		return protoreflect.ValueOfString("")
	case "ardaos.loan.McaMetadata.estimatedTermDays":
		return protoreflect.ValueOfUint32(uint32(0))
	case "ardaos.loan.McaMetadata.totalPaybackAmount":
		return protoreflect.ValueOfUint64(uint64(0))
	case "ardaos.loan.McaMetadata.dailySalesAverage":
		return protoreflect.ValueOfUint64(uint64(0))
	case "ardaos.loan.McaMetadata.creator":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ardaos.loan.McaMetadata"))
		}
		panic(fmt.Errorf("message ardaos.loan.McaMetadata does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_McaMetadata) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in ardaos.loan.McaMetadata", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_McaMetadata) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_McaMetadata) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_McaMetadata) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_McaMetadata) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*McaMetadata)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Index)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.LoanId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.DailyCollectionPercentage)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.MerchantId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.ProcessorName)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.EstimatedTermDays != 0 {
			n += 1 + runtime.Sov(uint64(x.EstimatedTermDays))
		}
		if x.TotalPaybackAmount != 0 {
			n += 1 + runtime.Sov(uint64(x.TotalPaybackAmount))
		}
		if x.DailySalesAverage != 0 {
			n += 1 + runtime.Sov(uint64(x.DailySalesAverage))
		}
		l = len(x.Creator)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*McaMetadata)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Creator) > 0 {
			i -= len(x.Creator)
			copy(dAtA[i:], x.Creator)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Creator)))
			i--
			dAtA[i] = 0x4a
		}
		if x.DailySalesAverage != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.DailySalesAverage))
			i--
			dAtA[i] = 0x40
		}
		if x.TotalPaybackAmount != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.TotalPaybackAmount))
			i--
			dAtA[i] = 0x38
		}
		if x.EstimatedTermDays != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.EstimatedTermDays))
			i--
			dAtA[i] = 0x30
		}
		if len(x.ProcessorName) > 0 {
			i -= len(x.ProcessorName)
			copy(dAtA[i:], x.ProcessorName)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ProcessorName)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.MerchantId) > 0 {
			i -= len(x.MerchantId)
			copy(dAtA[i:], x.MerchantId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.MerchantId)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.DailyCollectionPercentage) > 0 {
			i -= len(x.DailyCollectionPercentage)
			copy(dAtA[i:], x.DailyCollectionPercentage)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.DailyCollectionPercentage)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.LoanId) > 0 {
			i -= len(x.LoanId)
			copy(dAtA[i:], x.LoanId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.LoanId)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Index) > 0 {
			i -= len(x.Index)
			copy(dAtA[i:], x.Index)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Index)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*McaMetadata)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: McaMetadata: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: McaMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Index = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field LoanId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.LoanId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field DailyCollectionPercentage", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.DailyCollectionPercentage = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field MerchantId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.MerchantId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ProcessorName", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ProcessorName = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 6:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field EstimatedTermDays", wireType)
				}
				x.EstimatedTermDays = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.EstimatedTermDays |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 7:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TotalPaybackAmount", wireType)
				}
				x.TotalPaybackAmount = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.TotalPaybackAmount |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 8:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field DailySalesAverage", wireType)
				}
				x.DailySalesAverage = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.DailySalesAverage |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 9:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Creator = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: ardaos/loan/mca_metadata.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type McaMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index                     string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	LoanId                    string `protobuf:"bytes,2,opt,name=loanId,proto3" json:"loanId,omitempty"`
	DailyCollectionPercentage string `protobuf:"bytes,3,opt,name=dailyCollectionPercentage,proto3" json:"dailyCollectionPercentage,omitempty"`
	MerchantId                string `protobuf:"bytes,4,opt,name=merchantId,proto3" json:"merchantId,omitempty"`
	ProcessorName             string `protobuf:"bytes,5,opt,name=processorName,proto3" json:"processorName,omitempty"`
	EstimatedTermDays         uint32 `protobuf:"varint,6,opt,name=estimatedTermDays,proto3" json:"estimatedTermDays,omitempty"`
	TotalPaybackAmount        uint64 `protobuf:"varint,7,opt,name=totalPaybackAmount,proto3" json:"totalPaybackAmount,omitempty"`
	DailySalesAverage         uint64 `protobuf:"varint,8,opt,name=dailySalesAverage,proto3" json:"dailySalesAverage,omitempty"`
	Creator                   string `protobuf:"bytes,9,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (x *McaMetadata) Reset() {
	*x = McaMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ardaos_loan_mca_metadata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *McaMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McaMetadata) ProtoMessage() {}

// Deprecated: Use McaMetadata.ProtoReflect.Descriptor instead.
func (*McaMetadata) Descriptor() ([]byte, []int) {
	return file_ardaos_loan_mca_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *McaMetadata) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *McaMetadata) GetLoanId() string {
	if x != nil {
		return x.LoanId
	}
	return ""
}

func (x *McaMetadata) GetDailyCollectionPercentage() string {
	if x != nil {
		return x.DailyCollectionPercentage
	}
	return ""
}

func (x *McaMetadata) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *McaMetadata) GetProcessorName() string {
	if x != nil {
		return x.ProcessorName
	}
	return ""
}

func (x *McaMetadata) GetEstimatedTermDays() uint32 {
	if x != nil {
		return x.EstimatedTermDays
	}
	return 0
}

func (x *McaMetadata) GetTotalPaybackAmount() uint64 {
	if x != nil {
		return x.TotalPaybackAmount
	}
	return 0
}

func (x *McaMetadata) GetDailySalesAverage() uint64 {
	if x != nil {
		return x.DailySalesAverage
	}
	return 0
}

func (x *McaMetadata) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

var File_ardaos_loan_mca_metadata_proto protoreflect.FileDescriptor

var file_ardaos_loan_mca_metadata_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x72, 0x64, 0x61, 0x6f, 0x73, 0x2f, 0x6c, 0x6f, 0x61, 0x6e, 0x2f, 0x6d, 0x63,
	0x61, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x61, 0x72, 0x64, 0x61, 0x6f, 0x73, 0x2e, 0x6c, 0x6f, 0x61, 0x6e, 0x22, 0xe5, 0x02,
	0x0a, 0x0b, 0x4d, 0x63, 0x61, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x61, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x6f, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x19, 0x64,
	0x61, 0x69, 0x6c, 0x79, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x65,
	0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x19,
	0x64, 0x61, 0x69, 0x6c, 0x79, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50,
	0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x65, 0x72,
	0x63, 0x68, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d,
	0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x2c, 0x0a, 0x11, 0x65, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x64, 0x54, 0x65, 0x72, 0x6d,
	0x44, 0x61, 0x79, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x11, 0x65, 0x73, 0x74, 0x69,
	0x6d, 0x61, 0x74, 0x65, 0x64, 0x54, 0x65, 0x72, 0x6d, 0x44, 0x61, 0x79, 0x73, 0x12, 0x2e, 0x0a,
	0x12, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x12, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x50, 0x61, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2c, 0x0a,
	0x11, 0x64, 0x61, 0x69, 0x6c, 0x79, 0x53, 0x61, 0x6c, 0x65, 0x73, 0x41, 0x76, 0x65, 0x72, 0x61,
	0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x11, 0x64, 0x61, 0x69, 0x6c, 0x79, 0x53,
	0x61, 0x6c, 0x65, 0x73, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x6f, 0x72, 0x42, 0x89, 0x01, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x72,
	0x64, 0x61, 0x6f, 0x73, 0x2e, 0x6c, 0x6f, 0x61, 0x6e, 0x42, 0x10, 0x4d, 0x63, 0x61, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x17, 0x61,
	0x72, 0x64, 0x61, 0x2d, 0x6f, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x72, 0x64, 0x61, 0x6f,
	0x73, 0x2f, 0x6c, 0x6f, 0x61, 0x6e, 0xa2, 0x02, 0x03, 0x41, 0x4c, 0x58, 0xaa, 0x02, 0x0b, 0x41,
	0x72, 0x64, 0x61, 0x6f, 0x73, 0x2e, 0x4c, 0x6f, 0x61, 0x6e, 0xca, 0x02, 0x0b, 0x41, 0x72, 0x64,
	0x61, 0x6f, 0x73, 0x5c, 0x4c, 0x6f, 0x61, 0x6e, 0xe2, 0x02, 0x17, 0x41, 0x72, 0x64, 0x61, 0x6f,
	0x73, 0x5c, 0x4c, 0x6f, 0x61, 0x6e, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0xea, 0x02, 0x0c, 0x41, 0x72, 0x64, 0x61, 0x6f, 0x73, 0x3a, 0x3a, 0x4c, 0x6f, 0x61,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ardaos_loan_mca_metadata_proto_rawDescOnce sync.Once
	file_ardaos_loan_mca_metadata_proto_rawDescData = file_ardaos_loan_mca_metadata_proto_rawDesc
)

func file_ardaos_loan_mca_metadata_proto_rawDescGZIP() []byte {
	file_ardaos_loan_mca_metadata_proto_rawDescOnce.Do(func() {
		file_ardaos_loan_mca_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_ardaos_loan_mca_metadata_proto_rawDescData)
	})
	return file_ardaos_loan_mca_metadata_proto_rawDescData
}

var file_ardaos_loan_mca_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ardaos_loan_mca_metadata_proto_goTypes = []interface{}{
	(*McaMetadata)(nil), // 0: ardaos.loan.McaMetadata
}
var file_ardaos_loan_mca_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ardaos_loan_mca_metadata_proto_init() }
func file_ardaos_loan_mca_metadata_proto_init() {
	if File_ardaos_loan_mca_metadata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ardaos_loan_mca_metadata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*McaMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ardaos_loan_mca_metadata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ardaos_loan_mca_metadata_proto_goTypes,
		DependencyIndexes: file_ardaos_loan_mca_metadata_proto_depIdxs,
		MessageInfos:      file_ardaos_loan_mca_metadata_proto_msgTypes,
	}.Build()
	File_ardaos_loan_mca_metadata_proto = out.File
	file_ardaos_loan_mca_metadata_proto_rawDesc = nil
	file_ardaos_loan_mca_metadata_proto_goTypes = nil
	file_ardaos_loan_mca_metadata_proto_depIdxs = nil
}
