# Documentation generation configuration for ArdaOS Compliance Compiler

project_name: "ArdaOS Compliance Compiler"
project_description: "Policy compilation and validation tool for ArdaOS blockchain compliance engine"
version: "1.0.0"
author: "ArdaOS Team"
license: "Apache-2.0"
repository: "https://github.com/ardaos/arda-os"
homepage: "https://ardaos.com"
docs_url: "https://docs.ardaos.com/compliance-compiler"

# Documentation sections to generate
sections:
  - name: "getting-started"
    title: "Getting Started"
    description: "Introduction and quick start guide"
    generate: true
    template: "getting-started.md.tmpl"
    order: 1

  - name: "installation"
    title: "Installation"
    description: "Installation instructions for different platforms"
    generate: true
    template: "installation.md.tmpl"
    order: 2

  - name: "cli-reference"
    title: "CLI Reference"
    description: "Complete CLI command reference"
    generate: true
    template: "cli-reference.md.tmpl"
    order: 3

  - name: "api-reference"
    title: "API Reference"
    description: "Go API documentation"
    generate: true
    template: "api-reference.md.tmpl"
    order: 4

  - name: "template-reference"
    title: "Template Reference"
    description: "Policy template documentation"
    generate: true
    template: "template-reference.md.tmpl"
    order: 5

  - name: "regulatory-frameworks"
    title: "Regulatory Frameworks"
    description: "Supported regulatory frameworks and compliance requirements"
    generate: true
    template: "regulatory-frameworks.md.tmpl"
    order: 6

  - name: "examples"
    title: "Examples"
    description: "Usage examples and tutorials"
    generate: true
    template: "examples.md.tmpl"
    order: 7

  - name: "integration"
    title: "Integration Guide"
    description: "Integration with ArdaOS and external systems"
    generate: true
    template: "integration.md.tmpl"
    order: 8

  - name: "development"
    title: "Development Guide"
    description: "Development setup and contribution guidelines"
    generate: true
    template: "development.md.tmpl"
    order: 9

  - name: "troubleshooting"
    title: "Troubleshooting"
    description: "Common issues and solutions"
    generate: true
    template: "troubleshooting.md.tmpl"
    order: 10

# Template-specific configuration
templates:
  include_examples: true
  include_test_data: true
  generate_schemas: true

  supported_verticals:
    - "Credit Card Receivables"
    - "Installment Loans"
    - "Merchant Cash Advances"
    - "Equipment Leasing"
    - "Working Capital Loans"

  supported_jurisdictions:
    - "USA"
    - "USA-NY"
    - "USA-CA"
    - "USA-TX"
    - "EU"
    - "UK"
    - "Canada"
    - "Australia"

# Custom fields for documentation generation
custom_fields:
  company_name: "ArdaOS Inc."
  support_email: "support@ardaos.com"
  discord_invite: "https://discord.gg/ardaos"
  documentation_url: "https://docs.ardaos.com"
  github_issues: "https://github.com/ardaos/arda-os/issues"
  release_notes: "https://github.com/ardaos/arda-os/releases"

  # Regulatory resources
  cfpb_url: "https://www.consumerfinance.gov/"
  fdic_url: "https://www.fdic.gov/"
  occ_url: "https://www.occ.gov/"
  fed_url: "https://www.federalreserve.gov/"

  # Development resources
  go_version: "1.21+"
  cobra_url: "https://cobra.dev/"
  protobuf_url: "https://protobuf.dev/"
  docker_url: "https://www.docker.com/"
